[package]
name = "container_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.19.0", features = ["v4"]}
